var teamData = [
  {
    "address": null, 
    "city": "O Fallon", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc1094", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Hooked on Technology", 
    "name": "The Boeing Company/Boeing Employees Community Fund/Nidec Motor Corporation/Cuivre River Electrical Coop/Toyota/Unisys/Ameren Missouri/Missouri State Technical College&River City Robots", 
    "nickname": "Channel Cats", 
    "postal_code": "63366", 
    "rookie_year": 2003, 
    "state_prov": "Missouri", 
    "team_number": 1094, 
    "website": "http://channelcats.rivercityrobots.org/"
  }, 
  {
    "address": null, 
    "city": "O Fallon", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc1208", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Fearless", 
    "name": "The Boeing Company/Verizon Wireless/Lockheed Martin/SAIC & O Fallon High School", 
    "nickname": "Metool Brigade", 
    "postal_code": "62269", 
    "rookie_year": 2003, 
    "state_prov": "Illinois", 
    "team_number": 1208, 
    "website": "http://www.othsrobotics.com/"
  }, 
  {
    "address": null, 
    "city": "Iowa City", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc167", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "SPRING (Students Promoting Robotics and Inspiring New Generations) Into Action!", 
    "name": "Rockwell Collins/Aero Antenna Technology&Iowa City High School&West Senior High School", 
    "nickname": "Children of the Corn", 
    "postal_code": "52246", 
    "rookie_year": 1998, 
    "state_prov": "Iowa", 
    "team_number": 167, 
    "website": "http://www.icrobotics.org"
  }, 
  {
    "address": null, 
    "city": "Blue Springs", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc1785", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Blue Springs School District/Waddell & Reed/Lunar Bowl/Blue Ridge Bank & Trust/Double C Industries, Inc/Blue Ridge Physical Therapy/The Chocolate Spa/Up A Tree/Independence Classics & Freshman Ctr. - G. Baker Bldg. & Blue Springs High & Blue Springs South High", 
    "nickname": "Blue Springs Robocats", 
    "postal_code": "64015", 
    "rookie_year": 2006, 
    "state_prov": "Missouri", 
    "team_number": 1785, 
    "website": "http://www.bluespringsrobotics.net"
  }, 
  {
    "address": null, 
    "city": "Lees Summit", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc1987", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "WalMart/Staples Foundation/Reiman Foundation/Brunson Instruments/Show Me Controls/Kastle Grinding/KC Stem Alliance/80 20 Inc./Fastenal/Quintiles Innovex/Edwina Smith/Sean & Michelle Ahern/Lee's Summit Tribune/Grider Orthodontics/Stonehaus Winery/Jon Plaas in memory of Adam Stevens/James B. Stuelke/Painted with Powder/Wentworth Technology Solutions/Lone Oak Lawns/R&D Tool and Engineering/Allied Plastics/Laird Plastics/EMJ Metals/Westlake Ace Hardware/Git Hub&Lee'S Summit North High", 
    "nickname": "Broncobots", 
    "postal_code": "64086", 
    "rookie_year": 2007, 
    "state_prov": "Missouri", 
    "team_number": 1987, 
    "website": "http://www.teambroncobots.com"
  }, 
  {
    "address": null, 
    "city": "Dunlap", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2040", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "To grow leaders, FIRST you need a little DERT", 
    "name": "Caterpillar / TE Connectivity / ABB / Stellar Systems & Dunlap High School", 
    "nickname": "DERT - Dunlap Eagles Robotics Team", 
    "postal_code": "61525", 
    "rookie_year": 2007, 
    "state_prov": "Illinois", 
    "team_number": 2040, 
    "website": "http://www.dert2040.com/"
  }, 
  {
    "address": null, 
    "city": "Peoria", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2081", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "If it doesn't work, try something else.", 
    "name": "Advanced Technology Services/Caterpillar Inc/Martin Engineering/Wentzel Engraving/Uftring Chevrolet & Brimfield High School & Princeville High School & Peoria Notre Dame High School", 
    "nickname": "Icarus", 
    "postal_code": "61614", 
    "rookie_year": 2007, 
    "state_prov": "Illinois", 
    "team_number": 2081, 
    "website": "http://Icarus2081.org"
  }, 
  {
    "address": null, 
    "city": "Mendota Heights", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2177", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Non Scholae Sed Vitae", 
    "name": "Boston Scientific/PTC&Convent of the Visitation School", 
    "nickname": "The Robettes", 
    "postal_code": "55120", 
    "rookie_year": 2007, 
    "state_prov": "Minnesota", 
    "team_number": 2177, 
    "website": "http://www.therobettes.com"
  }, 
  {
    "address": null, 
    "city": "Overland Park", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc2410", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Do what you love; love what you do. Work hard for others; they'll do that for yo", 
    "name": "Blue Valley Educational Foundation/General Motors/Honeywell/Ryerson/Hantover&Blue Valley Center For Professional Studies", 
    "nickname": "Blue Valley CAPS Metal Mustang Robotics", 
    "postal_code": "66223", 
    "rookie_year": 2008, 
    "state_prov": "Kansas", 
    "team_number": 2410, 
    "website": "http://www.mmr2410.com/"
  }, 
  {
    "address": null, 
    "city": "St. Paul", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2450", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Cretin Derham Hall", 
    "nickname": "Raiderbots", 
    "postal_code": "55116", 
    "rookie_year": 2008, 
    "state_prov": "Minnesota", 
    "team_number": 2450, 
    "website": "http://team2450.org"
  }, 
  {
    "address": null, 
    "city": "Minneapolis", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2500", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Together, we WILL\u00a0build a new heroic future", 
    "name": "Coloplast/Boston Scientific/General Mills/The Bakken Museum/EJ Ajax & Sons Inc./Medtronic/NASA/St. Thomas University/Carlson Advisors LLP/Install This Sign and Awning Co./Loram/Girl Scouts of Minnesota and Wisconsin River Valleys/Shingle Creek Neighborhood Association/Saint Thomas University- Engineering Department/Minneapolis Public Schools Career and Technical Education/Dunwoody College of Technology/Patrick Henry High School Booster Club/GOFIRST/Patrick Henry High School Foundation&Henry Senior High", 
    "nickname": "Herobotics", 
    "postal_code": "55412", 
    "rookie_year": 2008, 
    "state_prov": "Minnesota", 
    "team_number": 2500, 
    "website": "http://heroboticsteam.moonfruit.com/"
  }, 
  {
    "address": null, 
    "city": "Duluth", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2512", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "I can do that", 
    "name": "Stewart Taylor Printing/Tricel Honeycomb/Lake Superior Consulting/Saturn Systems/Minnesota Power/F.I.Salter/National Bank of Commerce/AAR Aircraft Services Duluth/Kiwanis of Friendly Duluth/Krech Ojard & Associates Inc./ISD 709/Woodland Family Dental&East Senior High", 
    "nickname": "Duluth East Daredevils", 
    "postal_code": "55804", 
    "rookie_year": 2008, 
    "state_prov": "Minnesota", 
    "team_number": 2512, 
    "website": "http://www.daredevils2512.org"
  }, 
  {
    "address": null, 
    "city": "Rochester", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2530", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Building Kids Who Build Robots", 
    "name": "Medtronic Inc./IBM/Mayo Clinic & Mayo Senior High & Century Senior High & John Marshall Senior High", 
    "nickname": "Inconceivable", 
    "postal_code": "55904", 
    "rookie_year": 2008, 
    "state_prov": "Minnesota", 
    "team_number": 2530, 
    "website": "http://www.frcteam2530.org/index"
  }, 
  {
    "address": null, 
    "city": "St. Anthony", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2574", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "BOT <3   (BOT Love)", 
    "name": "Medtronic Foundation & St. Anthony Village Senior High", 
    "nickname": "RoboHuskie", 
    "postal_code": "55418", 
    "rookie_year": 2008, 
    "state_prov": "Minnesota", 
    "team_number": 2574, 
    "website": "http://www.robohuskie.com"
  }, 
  {
    "address": null, 
    "city": "Saint Peter", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc3018", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Medtronic/Gustavus Adolphus College/APT CNC/DLC, Inc/The Soderlund Family&Neighborhood Group", 
    "nickname": "Nordic Storm", 
    "postal_code": "56082", 
    "rookie_year": 2009, 
    "state_prov": "Minnesota", 
    "team_number": 3018, 
    "website": "http://www.nordicstorm.org/"
  }, 
  {
    "address": null, 
    "city": "Woodbury ", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc3206", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Thou Shalt Not Play Minecraft", 
    "name": "3M / Northern Tier / Woodbury Rotary Club / Harvey Vogel / Silver Bullet / Medtronic / Xcel Energy / Gerdau & Woodbury Senior High", 
    "nickname": "Royal T-Wrecks", 
    "postal_code": "55125", 
    "rookie_year": 2010, 
    "state_prov": "Minnesota", 
    "team_number": 3206, 
    "website": "http://www.royaltwrecks.org/"
  }, 
  {
    "address": null, 
    "city": "Silver Bay", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc3267", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "MedTronic/FIRST/Cooperative Light and Power/North Shore Oil and Propane/Lake Bank/Arrowhead Manufacturer and Fabricators Association/Julies Variety and Hardware/MN Carl Perkins, Lake Superior Consortium/North Shore Collaborative/LemonDrop Stop/Community members and supporters of Mariner Robotics/MN Power Foundation/North Shore Federal Credit Union/NorthWoods Family Grille/PTSO&Kelley Secondary", 
    "nickname": "Mariner Robotics", 
    "postal_code": "55614", 
    "rookie_year": 2010, 
    "state_prov": "Minnesota", 
    "team_number": 3267, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Kansas City", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc3528", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "For HIS Glory!", 
    "name": "Metropolitan Community College/IBM/Constance Tobin/Richard Baillif/KC STEM Alliance/Staples/Ply Gem/Platte Clay Electric/Show Me Controls/Laird Plastics&Home School", 
    "nickname": "Up Next", 
    "postal_code": "64120", 
    "rookie_year": 2011, 
    "state_prov": "Missouri", 
    "team_number": 3528, 
    "website": "http://teamupnext.com"
  }, 
  {
    "address": null, 
    "city": "Albert Lea", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc3633", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Medtronics/Albert Lea High School/Cargill/Jenson Autobody/ITC&Albert Lea Senior High", 
    "nickname": "Catalyst 3633", 
    "postal_code": "56007", 
    "rookie_year": 2011, 
    "state_prov": "Minnesota", 
    "team_number": 3633, 
    "website": "http://www.team3633.com"
  }, 
  {
    "address": null, 
    "city": "Ames", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc3928", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Aim Higher", 
    "name": "John Deere/Danfoss/Monsanto Fund/Quality Manufacturing Corporation/CIT Signature Transportation/Interstate All Battery Center - Ames/City of Ames Electric Services/Iowa 4H Foundation&Story County 4H", 
    "nickname": "Team Neutrino", 
    "postal_code": "50011", 
    "rookie_year": 2012, 
    "state_prov": "Iowa", 
    "team_number": 3928, 
    "website": "http://www.teamneutrino.org"
  }, 
  {
    "address": null, 
    "city": "Duluth", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4009", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Robotics is in our Blood!", 
    "name": "Lake Superior Consulting / Hartel's-DBJ Disposal / MN Power Employees Credit Union / Arrowhead Machinists / ISD 709 &Denfeld Senior High", 
    "nickname": "Denfeld DNA Robotics", 
    "postal_code": "55807", 
    "rookie_year": 2012, 
    "state_prov": "Minnesota", 
    "team_number": 4009, 
    "website": "http://denfeldrobotics4009.org"
  }, 
  {
    "address": null, 
    "city": "La Crosse", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4011", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Mathy Construction/Best Buy/Ingersol Rand&Aquinas High School", 
    "nickname": "\u03c0\u03c1b\u03bftic   (pi robotics) ", 
    "postal_code": "54601", 
    "rookie_year": 2012, 
    "state_prov": "Wisconsin", 
    "team_number": 4011, 
    "website": "http://7rrc.org/aquinas"
  }, 
  {
    "address": null, 
    "city": "Duluth", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4230", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "OPTUM/TriStar/Natural Resources Research Institute (NRRI)/Cirrus Aircraft&Duluth Marshall School", 
    "nickname": "TopperBots ", 
    "postal_code": "55811", 
    "rookie_year": 2012, 
    "state_prov": "Minnesota", 
    "team_number": 4230, 
    "website": "http://www.topperbots4230.com"
  }, 
  {
    "address": null, 
    "city": "Saint Peters", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc4329", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "One for All and All for One", 
    "name": "The Boeing Company/Microsoft/STEM2U Youth Programs/Lowe's Hardware of O'Fallon, MO/The Lutheran Foundation of St. Louis/EPC Computers/Kelly Casters/Time Station/Foobadap Imprinting/No Magic Software/Ball Aerospace and Technologies/Dassault Systems - Solid Works/Baker Engineering Corporation/Stauder Technologies&Lutheran High School of St Charles County", 
    "nickname": "Lutheran Roboteers", 
    "postal_code": "63376", 
    "rookie_year": 2012, 
    "state_prov": "Missouri", 
    "team_number": 4329, 
    "website": "http://www.4329roboteers.org"
  }, 
  {
    "address": null, 
    "city": "Saint Paul", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4506", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "3M/Motion Tech Automation/Reiling Construction/Brigid O'Malley&Hill Murray School", 
    "nickname": "PioNerds", 
    "postal_code": "55109", 
    "rookie_year": 2013, 
    "state_prov": "Minnesota", 
    "team_number": 4506, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Saint Paul", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4536", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "3M&Central Senior High", 
    "nickname": "MinuteBots", 
    "postal_code": "55104", 
    "rookie_year": 2013, 
    "state_prov": "Minnesota", 
    "team_number": 4536, 
    "website": "http://www.minutebots.org"
  }, 
  {
    "address": null, 
    "city": "Des Moines", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4646", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "John Deere/Des Moines Area Community College (DMACC)/Monsanto Fund/Quality Manufacturing Corporation/Scheufler Farms/Iowa STEAM Innovation Zone&4-H Youth Development Organization", 
    "nickname": "Team ASAP ", 
    "postal_code": "50311", 
    "rookie_year": 2013, 
    "state_prov": "Iowa", 
    "team_number": 4646, 
    "website": "http://www.team4646.org/"
  }, 
  {
    "address": null, 
    "city": "West Fargo", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4818", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "John Deere/Microsoft/North Dakota Space Grant Consortium/Scheels/Otter Tail Power/ND CTE Dept/Packer Backers/Molex/Diamond J Customs/JDP Automation/PTC/Butler/Cook Endodontics/Brenco Cleaning Equimpent/Midwest Coating Inc/BTD Custom Metal Work/Bell State Bank and Trust/Houston Engineering/SAE North Central Section/Ostroms Ace Hardware/Fargo 3D Printing/Gadget Garage/AIC Maintenance/Trail King Industries/Sanford Health/FM Engineers Club/Agassiz Chemical & Equipment/McNeilus Steel/FM Home and Patio/High Point Networks/Fargo Automation&West Fargo High School", 
    "nickname": "The Herd", 
    "postal_code": "58078", 
    "rookie_year": 2013, 
    "state_prov": "North Dakota", 
    "team_number": 4818, 
    "website": "http://wfrobotics.org"
  }, 
  {
    "address": null, 
    "city": "West Branch", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5041", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Designing Robots, Building Leaders", 
    "name": "Monsanto Fund/Rockwell Collins/Hoffman Family/Hoover Presidential Library/Twinkle Co&West Branch High School", 
    "nickname": "CyBears", 
    "postal_code": "52358", 
    "rookie_year": 2014, 
    "state_prov": "Iowa", 
    "team_number": 5041, 
    "website": "https://5041cybearrobotics.wordpress.com/"
  }, 
  {
    "address": null, 
    "city": "Cedar Falls", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc525", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Students Working Around Robotic Technology", 
    "name": "Cedar Falls Community Schools/John Deere/Monsanto Fund/DENSO International America, Inc./Rockwell Collins/Iowa State University College of Engineering/DISTek Integration, Inc/Hawkeye Tool and Die/Trekman Racing&Cedar Falls High School", 
    "nickname": "Swartdogs", 
    "postal_code": "50613", 
    "rookie_year": 2001, 
    "state_prov": "Iowa", 
    "team_number": 525, 
    "website": "http://www.525swartdogs.org"
  }, 
  {
    "address": null, 
    "city": "Faribault", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5434", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Tru Vue/Mercury/MRG/SolidWorks&Faribault Senior High", 
    "nickname": "Falcon Robotics", 
    "postal_code": "55021", 
    "rookie_year": 2015, 
    "state_prov": "Minnesota", 
    "team_number": 5434, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Spirit Lake", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5576", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Spirit Lake High School", 
    "nickname": "Team Terminator", 
    "postal_code": "51360", 
    "rookie_year": 2015, 
    "state_prov": "Iowa", 
    "team_number": 5576, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Madison", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5638", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "&Lac Qui Parle Valley Secondary", 
    "nickname": "LQPV Robotics", 
    "postal_code": "56256", 
    "rookie_year": 2015, 
    "state_prov": "Minnesota", 
    "team_number": 5638, 
    "website": "http://team5638.org"
  }, 
  {
    "address": null, 
    "city": "Esko", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5690", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Build it. Wire it. Program it.", 
    "name": "Rockwell Automation/Burns & McDonnell/Thrivent Financial/Minnesota Power Foundation/Lake Superior Carl Perkins Consortium/ALLETE Clean Energy/Nordex/Siemens/Minnesota Power Employees Credit Union&Esko High School", 
    "nickname": "SubZero Robotics", 
    "postal_code": "55733", 
    "rookie_year": 2015, 
    "state_prov": "Minnesota", 
    "team_number": 5690, 
    "website": "http://www.subzerorobotics.wordpress.com"
  }, 
  {
    "address": null, 
    "city": "Kansas City", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc5809", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "AMDG", 
    "name": "A. Zahner & Rockhurst High School", 
    "nickname": "The Jesubots", 
    "postal_code": "64114", 
    "rookie_year": 2016, 
    "state_prov": "Missouri", 
    "team_number": 5809, 
    "website": "http://www.jesubots.org/"
  }, 
  {
    "address": null, 
    "city": "Waterloo", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5837", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "We work for TiPS", 
    "name": "John Deere/Denso/Iowa Governor's STEM Advisory Council & West High School & East High School", 
    "nickname": "Unity4Tech", 
    "postal_code": "50703", 
    "rookie_year": 2016, 
    "state_prov": "Iowa", 
    "team_number": 5837, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Bennington", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5906", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "&Bennington Secondary School", 
    "nickname": "Titanium Badgers", 
    "postal_code": "68007", 
    "rookie_year": 2016, 
    "state_prov": "Nebraska", 
    "team_number": 5906, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Grinnell", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5935", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Iowa Governor's STEM Advisory Council/Grinnell-Newburg Community School District/Grinnell Mutual Reinsurance Company/Image First Signs/Pagliai's Italian Pizza/West Side Diner Family Restaurant/Grinnell Realty/Sumner Tree Service & Grinnell Community Senior High School", 
    "nickname": "Tech Tigers", 
    "postal_code": "50112", 
    "rookie_year": 2016, 
    "state_prov": "Iowa", 
    "team_number": 5935, 
    "website": "http://ghstechtigers.weebly.com/"
  }, 
  {
    "address": null, 
    "city": "Westbrook", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5991", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Wendorff Welding/Medtronic&Westbrook-Walnut Grove Secondary", 
    "nickname": "Chargers", 
    "postal_code": "56183", 
    "rookie_year": 2016, 
    "state_prov": "Minnesota", 
    "team_number": 5991, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Dike", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6164", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Monsanto /Iowa Governor's STEM Advisory Council/John Deere/FRC-First Robotics Competition/COMMUNITY FOUNDATION OF NORTHEAST IOWA/Mike Albers Construction/Yellow Jacket Enterprises, LLC/Dike-New Hartford CSD&Dike-New Hartford High School", 
    "nickname": "Moonshot Slaybots", 
    "postal_code": "50624", 
    "rookie_year": 2016, 
    "state_prov": "Iowa", 
    "team_number": 6164, 
    "website": "http://dnhrobotics.weebly.com/"
  }, 
  {
    "address": null, 
    "city": "Davenport", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6317", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Iowa Governor's STEM Advisory Council/John Deere/NASA/Davenport Community School District&West High School", 
    "nickname": "Disruptive Innovation", 
    "postal_code": "52804", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6317, 
    "website": "https://davenportwest.github.io/6317/"
  }, 
  {
    "address": null, 
    "city": "Manchester", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6320", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Iowa Governor's STEM Advisory Council/Royal Alliance Monaghan Financial Services, LTD. /Maquoketa Valle Coop/Loecke Building Services/Simon's Feed/Regional Medical Center/FIRST&West Delaware High School", 
    "nickname": "Iron Hawks", 
    "postal_code": "52057", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6320, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Aurora", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6359", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "NASA & Family/Community", 
    "nickname": "TechKnow Difficulties", 
    "postal_code": "68818", 
    "rookie_year": 2017, 
    "state_prov": "Nebraska", 
    "team_number": 6359, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Spencer", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6371", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Iowa Governor's STEM Advisory Council/Spencer Community School District&Spencer High School", 
    "nickname": "Spencer Robotics", 
    "postal_code": "51301", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6371, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Pleasant Hill", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6379", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "John Deere&Southeast Polk High School", 
    "nickname": "Terabyte of Ram", 
    "postal_code": "50327", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6379, 
    "website": "https://sites.google.com/a/southeastpolk.org/southeast-polk-first-robotics-competition/"
  }, 
  {
    "address": null, 
    "city": "Cedar Rapids", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6412", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Metro High School", 
    "nickname": "For Sale By Owner", 
    "postal_code": "52401", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6412, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Muscatine", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6420", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "NASA/Iowa Governor's STEM Advisory Council/Monsanto/John Deere/HNI Corporation -- Hon and Allsteel/Community Foundation of Greater Muscatine (CFGM)/TEAM Staffing Solutions/Hoffmann Inc./Kent Corporation&Muscatine High School", 
    "nickname": "Fire Island Robotics", 
    "postal_code": "52761", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6420, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Waterloo", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6455", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "NASA & Columbus High School", 
    "nickname": "The Coded Collective", 
    "postal_code": "50701", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6455, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Lenox", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6467", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Lenox High School", 
    "nickname": "Tiger Robotics", 
    "postal_code": "50851", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6467, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Blue Grass", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc648", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Dream, Believe, Achieve", 
    "name": "Arconic/John Deere/Wal-Mart and Sam's Club/Moline Foundation/Cobham/Monsanto&Moline Sr High School&Rock Island High School&Rivermont Collegiate&Pleasant Valley High School&North Scott Senior High School&Davenport West", 
    "nickname": "QC ELITE - Flaming Squirrels", 
    "postal_code": "52726", 
    "rookie_year": 2001, 
    "state_prov": "Iowa", 
    "team_number": 648, 
    "website": "http://www.qcelite.com/"
  }, 
  {
    "address": null, 
    "city": "Vinton", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6536", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "West High School", 
    "nickname": "TheDarkSide", 
    "postal_code": "52349", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6536, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "La Porte City", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6630", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "John Deere/FIRST/Iowa Governor's STEM Advisory Council&Union High School", 
    "nickname": "F.U.N.  (FieRCely Uknighted Nation)", 
    "postal_code": "50651", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6630, 
    "website": "http://6630fun.weebly.com/"
  }, 
  {
    "address": null, 
    "city": "Northwood", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc876", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "\"Opportunities don't happen. You create them.\"", 
    "name": "ND Space Grant/John Deere/Brent Pederson/Dr. Mary Aaland/Aneta Whitetail/Nrthwd Amer. Legion/Amer. Crystal Sugar/Nrthwd Mens Club/Ed and Sue Lloyd/Hatton Mens Club/Citizen's State Bank/Phil and Trish Gisi/ND CTEd&Northwood High School&Hatton High School", 
    "nickname": "Thunder Robotics", 
    "postal_code": "58267", 
    "rookie_year": 2002, 
    "state_prov": "North Dakota", 
    "team_number": 876, 
    "website": "https://sites.google.com/a/northwoodk12.com/thunder-robotic/home"
  }, 
  {
    "address": null, 
    "city": "Marion", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc967", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Rockwell Collins/Linn-Mar Booster Club/EHA/Iowa Fluid Power/Lindahl Marine Contractors, Inc./Linn-Mar Foundation/Conveyor Engineering/Bentley Manufacturing/Master Tool Mfg/D.A.D. Mfg Inc/Cargill/Verizon/Intermec/Linn County REC/CIPCO/McElroy Trust & Linn-Mar High School", 
    "nickname": "Iron Lions", 
    "postal_code": "52302", 
    "rookie_year": 2002, 
    "state_prov": "Iowa", 
    "team_number": 967, 
    "website": "http://www.lmrobotics.com"
  }
]